name: Ardrive Workflow
on: [push]
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
         npm install -g ardrive-cli --silent
         echo "Successfully Installed ardrive-cli"

      - name: Build the website
        run: |
         npm install --silent
         npm run build --silent

      - name: Uploading to ardrive
        run: |
          echo ${{ vars.WALLET_JSON}} | base64 -d > wallet.json
          python arsync_script.py -w wallet.json -d ${{ vars.DRIVE_ID}} -b ${{ vars.BUILD_EXPORT_NAME}} >> log.txt
          gh auth login --with-token <<< ${{ vars.G_TOKEN }}
          gh repo edit ${{ github.repository }} --description "$(cat log.txt)"
          echo "Please navigate to the link from description to access you decentralized website!"